# Introduction to NumPy

In [10]:
import numpy as np

### DataTypes and Attributes

In [11]:
#numPy's main datatype is ndarry (n dim array)

# Array, vector:
a1= np.array([1,2,3])
a1

# 1 dimensional
#shape: (1,3)   which means 1 row and 3 columns

array([1, 2, 3])

In [12]:
# array, matrix:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2

# 2 dimensional
#shape: (2,3)   which means 1 row and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# array, matrix:
a3 = np.array([[[1,2,3],
              [4,5,6]],
             [[7,8,9],
              [10,11,12]],
             [[13,14,15],
              [16,17,18]]])
a3

# 3 dimensional
#shape: (2,3, 3)   which means 2 row and 3 columns

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
type(a3)

numpy.ndarray