# Introduction to NumPy

In [33]:
import numpy as np

### DataTypes and Attributes

In [34]:
#numPy's main datatype is ndarry (n dim array)

# Array, vector:
a1= np.array([1,2,3])
a1

# 1 dimensional
#shape: (1,3)   which means 1 row and 3 columns

array([1, 2, 3])

In [35]:
# array, matrix:
a2 = np.array([[1,2,3.3],
              [4,5,6.5]])
a2

# 2 dimensional
#shape: (2,3)   which means 1 row and 3 columns

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
# array, matrix:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])
a3

# 3 dimensional
#shape: (2, 3, 3)   which means 2 row and 3 columns

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
type(a3)

numpy.ndarray

In [38]:
# To add image: ![](numpy_array.jpg)

![](numpy_array.jpg)

In [39]:
a1.shape

(3,)

In [40]:
a2.shape

(2, 3)

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [43]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [44]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [45]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Creating a DataFrame from umPy array

In [46]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### Creating numPy array

In [47]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [48]:
ones = np.ones((2,3))  # array with ones
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
zeros = np.zeros((2,3,3))  # array with zeros
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
range_array = np.arange(0,10,2)  # array with range (start,stop,step)
range_array

array([0, 2, 4, 6, 8])

In [51]:
random_array = np.random.randint(0, 10, (2,3,4))  # array with random int
random_array

array([[[6, 4, 3, 0],
        [5, 0, 9, 1],
        [9, 0, 6, 6]],

       [[2, 5, 0, 0],
        [5, 5, 6, 9],
        [6, 8, 5, 9]]])

In [52]:
random_array2 = np.random.random((2,3,4))  # array with random
random_array2

array([[[0.66876341, 0.46398521, 0.70350184, 0.1784754 ],
        [0.4626302 , 0.43921541, 0.90877734, 0.2537577 ],
        [0.57805291, 0.50838581, 0.28418041, 0.52769395]],

       [[0.9557273 , 0.25337037, 0.90306218, 0.58443779],
        [0.29624581, 0.60185282, 0.74216077, 0.26062796],
        [0.34668829, 0.47722608, 0.66817015, 0.28129537]]])

In [53]:
random_array3 = np.random.rand(2,3,4)  # array with random
random_array3

array([[[7.04001325e-01, 8.85363444e-01, 3.43390402e-01, 8.51309978e-01],
        [5.09865973e-01, 5.44226911e-01, 8.07720179e-01, 5.73327438e-01],
        [2.13776242e-01, 1.44527526e-04, 7.12015627e-01, 1.04141511e-01]],

       [[5.57474230e-01, 9.57611702e-01, 3.75789341e-01, 5.11682945e-01],
        [4.62529111e-01, 9.55985411e-01, 3.47329261e-01, 1.33560270e-01],
        [9.83509426e-01, 3.71402787e-02, 6.30040325e-01, 3.36711995e-01]]])

In [54]:
# Using random seed (this keep aligned with the seed)
np.random.seed(seed=52)
random_array4 = np.random.randint(0,10, (5,3))  # array with random int
random_array4

array([[5, 7, 6],
       [7, 0, 5],
       [3, 3, 1],
       [3, 1, 5],
       [1, 0, 0]])

### Viewing Arrays and Matrices

In [55]:
np.unique(random_array4)  #finds the unique elements in np array

array([0, 1, 3, 5, 6, 7])

In [56]:
a3, a3[1]

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]), array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [57]:
a4 = np.random.randint(10, size = (2,3,4,5))   # Arrays read from the last to first
a4

array([[[[6, 6, 7, 9, 4],
         [6, 7, 7, 7, 4],
         [2, 5, 4, 0, 1],
         [2, 5, 2, 6, 9]],

        [[6, 5, 0, 6, 8],
         [1, 9, 7, 1, 9],
         [6, 9, 9, 1, 5],
         [8, 4, 9, 0, 6]],

        [[7, 3, 7, 0, 0],
         [9, 5, 1, 9, 7],
         [6, 9, 7, 4, 7],
         [0, 1, 5, 1, 9]]],


       [[[4, 0, 9, 6, 3],
         [1, 8, 7, 6, 4],
         [6, 5, 8, 1, 0],
         [0, 7, 2, 0, 2]],

        [[2, 3, 4, 7, 0],
         [1, 0, 0, 3, 3],
         [4, 5, 1, 4, 1],
         [9, 0, 0, 2, 9]],

        [[9, 7, 9, 2, 9],
         [3, 1, 6, 9, 6],
         [9, 8, 5, 0, 8],
         [8, 9, 2, 6, 6]]]])

In [58]:
a4.ndim

4

### How to get the first 4 numbers of the inner most arrays

In [59]:
a4[:, :, :, 4]

array([[[4, 4, 1, 9],
        [8, 9, 5, 6],
        [0, 7, 7, 9]],

       [[3, 4, 0, 2],
        [0, 3, 1, 9],
        [9, 6, 8, 6]]])

In [60]:
a4[:, :, :, 3]  #first 3 numbers of the inner most arrays

array([[[9, 7, 0, 6],
        [6, 1, 1, 0],
        [0, 9, 4, 1]],

       [[6, 6, 1, 0],
        [7, 3, 4, 2],
        [2, 9, 0, 6]]])

In [61]:
a4[:, :, 3, :]

array([[[2, 5, 2, 6, 9],
        [8, 4, 9, 0, 6],
        [0, 1, 5, 1, 9]],

       [[0, 7, 2, 0, 2],
        [9, 0, 0, 2, 9],
        [8, 9, 2, 6, 6]]])

## Manupulate and Comparing Arrays

### Arithmatic

In [62]:
a1

array([1, 2, 3])

In [63]:
ones = np.ones(3)

In [64]:
a1+ones

array([2., 3., 4.])

In [65]:
a1*ones

array([1., 2., 3.])

In [66]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [ ]:
a